### ISSUE TITLE
Add -o arguments

### ISSUE THREAD

**Issue by maboiteaspam** [thlorenz/exorcist#22]
Hi @thlorenz,

How do you think about adding -o arguments for JS content ~~and MAP content, need two arguments~~.

I m looking for that because i have some troubles to pipe cli stdout / stderr on windows.

Please let me know, so that i will fork or PR depending!

**Comment by maboiteaspam** [comment]
I was also needing input arg. So i made another PR. Just let me know please.

**Comment by jasonkarns** [comment]
This benefit wouldn't be limited to windows users. I use npm scripts heavily, and one feature in particular: the ability to send arbitrary arguments to the script by passing additional arguments to npm.

Assume an npm build script `foo` that simply executes `bar`. `npm run foo` translates to `bar`. To pass additional args to `bar`: `npm run foo -- --baz` translates to `bar --baz`.

npm does this by simply tacking on any additional args to the end of the script. However, if the npm script involves redirecting STDOUT to a file (as is necessary with exorcist), then you can't pass additional args to the npm script because npm appends them *after* the STDOUT redirection.

Given an npm script `exorcist` as `cat input.js | exorcist source.map > output.js`, attempting to run `npm run exorcist -- --foo` actually runs `cat input.js | exorcist source.map > output.js --foo` which is nonsensical.

**Comment by jasonkarns** [comment]
This feature is also necessary in order to allow overwriting the source js file. `cat foo.js | exorcist out.map > foo.js` fails because the shell will wipe `foo.js` (to prepare for appending) prior to `cat` having run.

**Comment by maboiteaspam** [comment]
interesting :+1:
