### ISSUE TITLE
Does not fail correctly

### ISSUE THREAD

**Issue by jacwright** [thlorenz/exorcist#31]
When there is an error in browserify, exorcist swallows it and doesn't exit with an error code. For example, if you have a JavaScript error in your source code, browserify will exit with an exit code of 1. This is correct behavior when there is an error and works with make and build systems to know it failed.

When piping to exorcist, the JS error is swallowed and an exit code of 0 for success is returned. So build systems assume the build was successful, but no file is created.

The log to the console is:
> The code that you piped into exorcist contains no source map!
Therefore it was piped through as is and no external map file generated.

Exorcist should exit with an exit code of 1 if the code is empty. This will allow to fail silently if there is no map, but not fail silently if there is no javascript (a sure sign that there was an error upstream).

This issue is regarding command-line usage.

```
browserify main.js --debug | exorcist bundle.js.map > bundle.js
```

**Comment by abritinthebay** [comment]
Isn't that an issue with piping the output thought? Like... the pipe is of nothing so al exorcist knows is that it got nothing.

**Comment by jacwright** [comment]
True. Can stdin tell if the previous stream was a stdout or stderr? Can exorcist tell if an error occurred and pass it along? We need a correct error exit code to work properly in continuous integration systems.

**Comment by abritinthebay** [comment]
Good question. Sadly I don't know enough about stdin/stdout to answer that one.

**Comment by meeber** [comment]
Now that https://github.com/thlorenz/exorcist/pull/34 has been merged, I plan on following up within a couple days with another small PR that addresses this issue. What I'm thinking is a non-breaking change hidden behind a new CLI option that causes exorcist to error (with a non-zero exit code) instead of warn if no source map file is created.

This would resolve my own CI issues (currently my build scripts manually verify the existence of the generated source map file whenever exorcist is used). Does this approach work for you guys?

**Comment by abritinthebay** [comment]
I'm ok with it but it's @thlorenz that needs to sign off on it :)
